import { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { AlertBanner } from './components/AlertBanner';
import { GaugeCard } from './components/GaugeCard';
import { CanaryCard } from './components/CanaryCard';
import { DivergenceChart } from './components/DivergenceChart';
import { AiAnalysisCard } from './components/AiAnalysisCard';
import { mockCanaryStatus, mockDivergenceData } from './utils/mockData';
import type { CanaryStatus } from './types/canary';
import './index.css';

function App() {
  const [status, setStatus] = useState<CanaryStatus | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadData = async () => {
      try {
        // Try fetching the real JSON generated by Python GitHub Actions
        const response = await fetch('/Canary-in-the-Financial-Crisis/data/canary_status.json');
        if (response.ok) {
          const data = await response.json();
          setStatus(data);
        } else {
          // Fallback to mock data for local development if json is missing
          console.warn('Real data not found, falling back to mock data.');
          setStatus(mockCanaryStatus);
        }
      } catch (error) {
        console.error('Failed to fetch canary data:', error);
        setStatus(mockCanaryStatus); // Fallback
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  if (loading || !status) {
    return (
      <div className="container flex items-center justify-center" style={{ minHeight: '100vh' }}>
        <h2 className="heading-lg text-secondary glow-yellow">Initializing Canary Systems...</h2>
      </div>
    );
  }

  return (
    <div className="container">
      <Header overallLevel={status.overallLevel} lastUpdated={status.lastUpdated} />
      
      <AlertBanner alerts={status.activeAlerts} />
      
      <div className="grid grid-cols-1" style={{ gap: '3rem' }}>
        
        {/* Top Row: AI Analysis and Gauge */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div className="lg:col-span-1">
            <GaugeCard score={status.overallScore} level={status.overallLevel} />
          </div>
          <div className="lg:col-span-2">
            <AiAnalysisCard analysis={status.aiAnalysis} />
          </div>
        </div>

        {/* Second Row: Divergence Chart */}
        <div className="grid grid-cols-1 gap-6">
          <DivergenceChart 
            title="Divergence: S&P500 vs Credit Health (HYG/LQD)"
            data={mockDivergenceData} // Kept mock for now as historical charting requires separate time-series json
            line1Key="sp500"
            line1Name="S&P 500"
            line1Color="var(--accent-blue)"
            line2Key="hygLqd"
            line2Name="HYG/LQD Ratio"
            line2Color="var(--accent-red)"
          />
        </div>

        {/* Section 1: Real-Time Market Canaries */}
        <div>
          <h2 className="heading-xl text-primary" style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ width: '8px', height: '32px', backgroundColor: 'var(--accent-blue)', display: 'inline-block', borderRadius: '4px' }}></span>
            Real-Time Market Canaries
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {/* Credit Stream */}
            <div className="indicator-group">
              <h3 className="heading-md" style={{ marginBottom: '0.5rem', borderBottom: '1px solid var(--card-border)', paddingBottom: '0.5rem' }}>Credit Stream</h3>
              {status.indicators.realtime.credit.map(indicator => (
                <CanaryCard key={indicator.id} indicator={indicator} />
              ))}
            </div>
            
            {/* Macro Stream */}
            <div className="indicator-group">
              <h3 className="heading-md" style={{ marginBottom: '0.5rem', borderBottom: '1px solid var(--card-border)', paddingBottom: '0.5rem' }}>Macro Stream</h3>
              {status.indicators.realtime.macro.map(indicator => (
                <CanaryCard key={indicator.id} indicator={indicator} />
              ))}
            </div>

            {/* Banking & Real Estate */}
            <div className="indicator-group">
              <h3 className="heading-md" style={{ marginBottom: '0.5rem', borderBottom: '1px solid var(--card-border)', paddingBottom: '0.5rem' }}>Banking / Real Estate</h3>
              {status.indicators.realtime.banking.map(indicator => (
                <CanaryCard key={indicator.id} indicator={indicator} />
              ))}
            </div>
          </div>
        </div>

        {/* Section 2: Macro Fundamentals (Monthly/Delayed) */}
        <div style={{ marginTop: '1rem' }}>
          <h2 className="heading-xl text-primary" style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <span style={{ width: '8px', height: '32px', backgroundColor: 'var(--accent-orange)', display: 'inline-block', borderRadius: '4px' }}></span>
            Macro Fundamentals (Monthly/Delayed)
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {status.indicators.fundamentals.map(indicator => (
              <CanaryCard key={indicator.id} indicator={indicator} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
